# Generated by Django 5.0.1 on 2024-03-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together=set(),
        ),
    ]
