# Generated by Django 5.0.1 on 2024-03-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_presenca_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.aula'),
        ),
    ]
