# Generated by Django 5.0.1 on 2024-03-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_aluno_email_alter_turma_disciplina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desistencia', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.aluno')),
            ],
            options={
                'db_table': 'desistencia',
            },
        ),
    ]
