# Generated by Django 5.0.1 on 2024-03-18 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_desistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='matricula',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='matricula',
            name='desistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Desistencia',
        ),
    ]
