# Generated by Django 5.0.1 on 2024-03-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_remove_matricula_data_inicio_matricula_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema.aluno'),
        ),
    ]
