# Generated by Django 5.0.3 on 2024-03-20 16:58

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_matricula_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
    ]
